/**
 * @license Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or http://ckeditor.com/license
 */

CKEDITOR.plugins.add( 'smiley', {
	requires: 'dialog',
	// jscs:disable maximumLineLength
	lang: 'af,ar,az,bg,bn,bs,ca,cs,cy,da,de,de-ch,el,en,en-au,en-ca,en-gb,eo,es,et,eu,fa,fi,fo,fr,fr-ca,gl,gu,he,hi,hr,hu,id,is,it,ja,ka,km,ko,ku,lt,lv,mk,mn,ms,nb,nl,no,oc,pl,pt,pt-br,ro,ru,si,sk,sl,sq,sr,sr-latn,sv,th,tr,tt,ug,uk,vi,zh,zh-cn', // %REMOVE_LINE_CORE%
	// jscs:enable maximumLineLength
	icons: 'smiley', // %REMOVE_LINE_CORE%
	hidpi: true, // %REMOVE_LINE_CORE%
	init: function( editor ) {
		editor.config.smiley_path = editor.config.smiley_path || ( this.path + 'images/' );
		editor.addCommand( 'smiley', new CKEDITOR.dialogCommand( 'smiley', {
			allowedContent: 'img[alt,height,!src,title,width]',
			requiredContent: 'img'
		} ) );
		editor.ui.addButton && editor.ui.addButton( 'Smiley', {
			label: editor.lang.smiley.toolbar,
			command: 'smiley',
			toolbar: 'insert,50'
		} );
		CKEDITOR.dialog.add( 'smiley', this.path + 'dialogs/smiley.js' );
	}
} );

/**
 * The base path used to build the URL for the smiley images. It must end with a slash.
 *
 *		config.smiley_path = 'http://www.example.com/images/smileys/';
 *
 *		config.smiley_path = '/images/smileys/';
 *
 * @cfg {String} [smiley_path=CKEDITOR.basePath + 'plugins/smiley/images/']
 * @member CKEDITOR.config
 */

/**
 * The file names for the smileys to be displayed. These files must be
 * contained inside the URL path defined with the {@link #smiley_path} setting.
 *
 *		// This is actually the default value.
 *		config.smiley_images = [
 *			'regular_smile.png','sad_smile.png','wink_smile.png','teeth_smile.png','confused_smile.png','tongue_smile.png',
 *			'embarrassed_smile.png','omg_smile.png','whatchutalkingabout_smile.png','angry_smile.png','angel_smile.png','shades_smile.png',
 *			'devil_smile.png','cry_smile.png','lightbulb.png','thumbs_down.png','thumbs_up.png','heart.png',
 *			'broken_heart.png','kiss.png','envelope.png'
 *		];
 *
 * @cfg
 * @member CKEDITOR.config
 */
CKEDITOR.config.smiley_images = [
	'image_emoticon.png', 'image_emoticon2.png', 'image_emoticon3.png', 'image_emoticon83.png', 'image_emoticon5.png', 'image_emoticon6.png',
	'image_emoticon7.png', 'image_emoticon8.png', 'image_emoticon9.png', 'image_emoticon10.png', 'image_emoticon11.png', 'image_emoticon12.png',
	'image_emoticon13.png', 'image_emoticon14.png', 'image_emoticon15.png', 'image_emoticon16.png', 'image_emoticon17.png', 'image_emoticon18.png',
	'image_emoticon19.png', 'image_emoticon20.png', 'image_emoticon21.png', 'image_emoticon22.png', 'image_emoticon23.png', 'image_emoticon24.png',
	'image_emoticon25.png', 'image_emoticon26.png', 'image_emoticon27.png', 'image_emoticon28.png', 'image_emoticon29.png', 'image_emoticon30.png',
	'image_emoticon31.png', 'image_emoticon32.png', 'image_emoticon33.png', 'image_emoticon34.png', 'image_emoticon35.png', 'image_emoticon36.png',
	'image_emoticon42.png', 'image_emoticon37.png', 'image_emoticon38.png', 'image_emoticon39.png', 'image_emoticon40.png', 'image_emoticon41.png',
	'image_emoticon43.png', 'image_emoticon44.png', 'image_emoticon45.png', 'image_emoticon46.png', 'image_emoticon47.png', 'image_emoticon48.png',
	'image_emoticon49.png', 'image_emoticon50.png', 'image_emoticon61.png', 'image_emoticon62.png', 'image_emoticon63.png', 'image_emoticon64.png',
	'image_emoticon65.png', 'image_emoticon66.png', 'image_emoticon67.png', 'image_emoticon68.png', 'image_emoticon69.png', 'image_emoticon70.png',
	'image_emoticon71.png', 'image_emoticon72.png', 'image_emoticon73.png', 'image_emoticon74.png', 'image_emoticon75.png', 'image_emoticon76.png',
	'image_emoticon77.png', 'image_emoticon78.png', 'image_emoticon79.png', 'image_emoticon80.png', 'image_emoticon81.png', 'image_emoticon82.png'
];

/**
 * The description to be used for each of the smileys defined in the
 * {@link CKEDITOR.config#smiley_images} setting. Each entry in this array list
 * must match its relative pair in the {@link CKEDITOR.config#smiley_images}
 * setting.
 *
 *		// Default settings.
 *		config.smiley_descriptions = [
 *			'smiley', 'sad', 'wink', 'laugh', 'frown', 'cheeky', 'blush', 'surprise',
 *			'indecision', 'angry', 'angel', 'cool', 'devil', 'crying', 'enlightened', 'no',
 *			'yes', 'heart', 'broken heart', 'kiss', 'mail'
 *		];
 *
 *		// Use textual emoticons as description.
 *		config.smiley_descriptions = [
 *			':)', ':(', ';)', ':D', ':/', ':P', ':*)', ':-o',
 *			':|', '>:(', 'o:)', '8-)', '>:-)', ';(', '', '', '',
 *			'', '', ':-*', ''
 *		];
 *
 * @cfg
 * @member CKEDITOR.config
 */
CKEDITOR.config.smiley_descriptions = [];

/**
 * The number of columns to be generated by the smilies matrix.
 *
 *		config.smiley_columns = 6;
 *
 * @since 3.3.2
 * @cfg {Number} [smiley_columns=8]
 * @member CKEDITOR.config
 */
